services:
  postgres:
    image: postgres:15
    container_name: attendance_db
    environment:
      POSTGRES_DB: attendance_management
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d attendance_management"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - attendance-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: attendance_app
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/attendance_management
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: user
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: true
    networks:
      - attendance-network
    restart: unless-stopped

networks:
  attendance-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
