server:
  port: 8080

spring:
  application:
    name: attendance-management
  datasource:
    url: jdbc:postgresql://localhost:5432/attendance_management
    username: user
    password: user
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

logging:
  config: classpath:logback-spring.xml
  level:
    root: INFO
    com:
      attendance: DEBUG
    org:
      springframework: INFO
      hibernate: INFO
  file:
    name: ./log/${spring.application.name}-${server.port}.log
    max-size: 10MB
    max-history: 30 